<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Category::insert([
            ['category_id' => 'CAT001', 'subcategory_name' => 'Category 1', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT002', 'subcategory_name' => 'Category 2', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT003', 'subcategory_name' => 'Category 3', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT004', 'subcategory_name' => 'Category 4', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT005', 'subcategory_name' => 'Category 5', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT006', 'subcategory_name' => 'Category 6', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT007', 'subcategory_name' => 'Category 7', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT008', 'subcategory_name' => 'Category 8', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT009', 'subcategory_name' => 'Category 9', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT010', 'subcategory_name' => 'Category 10', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT011', 'subcategory_name' => 'Category 11', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT012', 'subcategory_name' => 'Category 12', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT013', 'subcategory_name' => 'Category 13', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT014', 'subcategory_name' => 'Category 14', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT015', 'subcategory_name' => 'Category 15', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT016', 'subcategory_name' => 'Category 16', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT017', 'subcategory_name' => 'Category 17', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT018', 'subcategory_name' => 'Category 18', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT019', 'subcategory_name' => 'Category 19', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT020', 'subcategory_name' => 'Category 20', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT021', 'subcategory_name' => 'Category 21', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT022', 'subcategory_name' => 'Category 22', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT023', 'subcategory_name' => 'Category 23', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT024', 'subcategory_name' => 'Category 24', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT025', 'subcategory_name' => 'Category 25', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT026', 'subcategory_name' => 'Category 26', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT027', 'subcategory_name' => 'Category 27', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT028', 'subcategory_name' => 'Category 28', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT029', 'subcategory_name' => 'Category 29', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT030', 'subcategory_name' => 'Category 30', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT031', 'subcategory_name' => 'Category 31', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT032', 'subcategory_name' => 'Category 32', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT033', 'subcategory_name' => 'Category 33', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT034', 'subcategory_name' => 'Category 34', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT035', 'subcategory_name' => 'Category 35', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT036', 'subcategory_name' => 'Category 36', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT037', 'subcategory_name' => 'Category 37', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT038', 'subcategory_name' => 'Category 38', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT039', 'subcategory_name' => 'Category 39', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT040', 'subcategory_name' => 'Category 40', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT041', 'subcategory_name' => 'Category 41', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT042', 'subcategory_name' => 'Category 42', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT043', 'subcategory_name' => 'Category 43', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT044', 'subcategory_name' => 'Category 44', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT045', 'subcategory_name' => 'Category 45', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT046', 'subcategory_name' => 'Category 46', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT047', 'subcategory_name' => 'Category 47', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT048', 'subcategory_name' => 'Category 48', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT049', 'subcategory_name' => 'Category 49', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT050', 'subcategory_name' => 'Category 50', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT051', 'subcategory_name' => 'Category 51', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT052', 'subcategory_name' => 'Category 52', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT053', 'subcategory_name' => 'Category 53', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT054', 'subcategory_name' => 'Category 54', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT055', 'subcategory_name' => 'Category 55', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT056', 'subcategory_name' => 'Category 56', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT057', 'subcategory_name' => 'Category 57', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT058', 'subcategory_name' => 'Category 58', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT059', 'subcategory_name' => 'Category 59', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT060', 'subcategory_name' => 'Category 60', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT061', 'subcategory_name' => 'Category 61', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT062', 'subcategory_name' => 'Category 62', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT063', 'subcategory_name' => 'Category 63', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT064', 'subcategory_name' => 'Category 64', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT065', 'subcategory_name' => 'Category 65', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT066', 'subcategory_name' => 'Category 66', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT067', 'subcategory_name' => 'Category 67', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT068', 'subcategory_name' => 'Category 68', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT069', 'subcategory_name' => 'Category 69', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT070', 'subcategory_name' => 'Category 70', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT071', 'subcategory_name' => 'Category 71', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT072', 'subcategory_name' => 'Category 72', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT073', 'subcategory_name' => 'Category 73', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT074', 'subcategory_name' => 'Category 74', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT075', 'subcategory_name' => 'Category 75', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT076', 'subcategory_name' => 'Category 76', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT077', 'subcategory_name' => 'Category 77', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT078', 'subcategory_name' => 'Category 78', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT079', 'subcategory_name' => 'Category 79', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT080', 'subcategory_name' => 'Category 80', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT081', 'subcategory_name' => 'Category 81', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT082', 'subcategory_name' => 'Category 82', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT083', 'subcategory_name' => 'Category 83', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT084', 'subcategory_name' => 'Category 84', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT085', 'subcategory_name' => 'Category 85', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT086', 'subcategory_name' => 'Category 86', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT087', 'subcategory_name' => 'Category 87', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT088', 'subcategory_name' => 'Category 88', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT089', 'subcategory_name' => 'Category 89', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT090', 'subcategory_name' => 'Category 90', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT091', 'subcategory_name' => 'Category 91', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT092', 'subcategory_name' => 'Category 92', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT093', 'subcategory_name' => 'Category 93', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT094', 'subcategory_name' => 'Category 94', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT095', 'subcategory_name' => 'Category 95', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT096', 'subcategory_name' => 'Category 96', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT097', 'subcategory_name' => 'Category 97', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT098', 'subcategory_name' => 'Category 98', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT099', 'subcategory_name' => 'Category 99', 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 'CAT100', 'subcategory_name' => 'Category 100', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
